// ════════════════════════════════════════════════════════════
// CRITICAL CSS MANIFEST — per page, which selectors from
// css/styles.css and which selectors from the page's own local
// (non-critical) <style> block belong in its critical-css block.
// Seeded once from the previously hand-copied blocks via
// scripts/critical-css/discover.mjs, then hand-reviewed. Edit
// this file to add/remove what's critical for a page; run
// `node scripts/critical-css/build.mjs` to regenerate the actual
// <style id="critical-css"> markup from the real sources.
// ════════════════════════════════════════════════════════════
export const PAGES = {
  "about.html": {
    "chatWidget": true,
    "stylesCss": [
      "*, *::before, *::after",
      "html, body",
      "img",
      "button",
      "a",
      ":root",
      "body",
      ".site-shell",
      ".page-stack",
      ".site-nav",
      ".nav-pill",
      ".nav-link",
      ".nav-link::after",
      ".nav-link:hover",
      ".nav-link:hover::after",
      ".nav-link.active",
      ".contact-widget",
      ".contact-widget-btn",
      ".contact-widget-btn:hover",
      ".contact-widget-ava-wrap",
      ".contact-widget-avatar",
      ".contact-widget-avatar img",
      ".contact-widget-dot",
      ".contact-widget-text",
      ".contact-widget-title",
      ".contact-widget-online",
      ".about-page-header",
      ".about-page-header h1",
      ".about-card",
      ".about-identity",
      ".about-avatar-wrap",
      ".about-avatar-wrap::after",
      ".about-avatar-wrap img",
      ".about-identity-text",
      ".about-name",
      ".about-title",
      ".about-story",
      ".about-bio",
      ".about-link",
      ".about-link:hover",
      ".page-stack--about",
      ".mobile-top",
      ".mobile-wordmark",
      ".mobile-burger",
      ".mobile-burger:active",
      ".burger-bar",
      ".mobile-nav-overlay",
      ".mobile-nav-link",
      ".mobile-nav-link:hover, .mobile-nav-link:active"
    ],
    "local": [],
    "localAtomics": []
  },
  "advantages.html": {
    "chatWidget": true,
    "stylesCss": [
      "*, *::before, *::after",
      "html, body",
      "img",
      "button",
      "a",
      ":root",
      "body",
      ".site-shell",
      ".page-stack",
      ".site-nav",
      ".nav-pill",
      ".nav-link",
      ".nav-link::after",
      ".nav-link:hover",
      ".nav-link:hover::after",
      ".nav-link.active",
      ".contact-widget",
      ".contact-widget-btn",
      ".contact-widget-btn:hover",
      ".contact-widget-ava-wrap",
      ".contact-widget-avatar",
      ".contact-widget-avatar img",
      ".contact-widget-dot",
      ".contact-widget-text",
      ".contact-widget-title",
      ".contact-widget-online",
      ".advantages",
      ".adv-list",
      ".adv-card",
      ".adv-card::after",
      ".adv-card.adv-card--hl-both::after",
      ".adv-img-wrap",
      ".adv-img-wrap img",
      ".adv-card:hover .adv-img-wrap img",
      ".adv-content",
      ".adv-title",
      ".adv-short",
      ".adv-long",
      ".adv-long:not(.open)::after",
      ".adv-long p",
      ".adv-toggle",
      ".adv-toggle:hover",
      ".mobile-top",
      ".mobile-wordmark",
      ".mobile-burger",
      ".mobile-burger:active",
      ".burger-bar",
      ".mobile-nav-overlay",
      ".mobile-nav-link",
      ".mobile-nav-link:hover, .mobile-nav-link:active"
    ],
    "local": [
      ".adv-card:nth-of-type(2n+1)::after",
      ".adv-page-hero",
      ".adv-page-hero h1",
      ".adv-page-hero p"
    ],
    "localAtomics": []
  },
  "client-care.html": {
    "chatWidget": true,
    "stylesCss": [
      "*, *::before, *::after",
      "html, body",
      "img",
      "button",
      "a",
      ":root",
      "body",
      ".site-shell",
      ".page-stack",
      ".site-nav",
      ".nav-pill",
      ".nav-link",
      ".nav-link::after",
      ".nav-link:hover",
      ".nav-link:hover::after",
      ".nav-link.active",
      ".contact-widget",
      ".contact-widget-btn",
      ".contact-widget-btn:hover",
      ".contact-widget-ava-wrap",
      ".contact-widget-avatar",
      ".contact-widget-avatar img",
      ".contact-widget-dot",
      ".contact-widget-text",
      ".contact-widget-title",
      ".contact-widget-online",
      ".mobile-top",
      ".mobile-wordmark",
      ".mobile-burger",
      ".mobile-burger:active",
      ".burger-bar",
      ".mobile-nav-overlay",
      ".mobile-nav-link",
      ".mobile-nav-link:hover, .mobile-nav-link:active"
    ],
    "local": [
      ".cc-hero",
      ".cc-hero h1",
      ".cc-hero p",
      ".cc-chat-wrap",
      ".cc-chat",
      ".cc-chat-hdr",
      ".cc-chat-hdr-avatar",
      ".cc-hdr-ava-img",
      ".cc-chat-hdr-avatar img",
      ".cc-chat-hdr-avatar-dot",
      ".cc-chat-hdr-avatar-dot.dot-on",
      ".cc-chat-hdr-info",
      ".cc-chat-hdr-name",
      ".cc-chat-hdr-status",
      ".cc-chat-hdr-status.status-on",
      ".cc-chat-hdr-status-text",
      ".cc-hdr-online-line",
      ".cc-chat-hdr-status-dot",
      ".cc-chat-hdr-status-dot.dot-on",
      ".cc-chat-msgs",
      "#chatMsgs",
      ".cc-msg",
      ".cc-msg--mgr",
      ".cc-msg-ava",
      ".cc-msg-ava img",
      ".cc-msg-bubble",
      ".cc-msg--mgr .cc-msg-bubble",
      ".cc-msg--mgr .cc-msg-bubble::after",
      ".cc-msg-time",
      ".cc-msg--mgr .cc-msg-time",
      ".cc-chat-input-row",
      ".cc-chat-input",
      ".cc-chat-input::placeholder",
      ".cc-chat-input:focus",
      ".cg-input-wrap",
      ".cg-input-wrap .cc-chat-input",
      ".cg-input-wrap .cc-chat-input:focus",
      ".cc-chat-send",
      ".cc-chat-send:hover",
      ".cc-chat-send:active",
      ".cc-chat-send svg",
      ".cc-dual-chat",
      ".cc-dual-chat .cc-chat-column",
      ".cc-dual-chat .cc-chat-wrap",
      ".cc-chat--primary .cc-chat-hdr",
      ".cc-chat--primary .cc-chat-input-row",
      ".cc-chat--primary .cc-chat-hdr-avatar",
      ".cc-chat--primary .cc-chat-hdr-avatar-dot",
      ".cc-divider",
      ".cc-channels"
    ],
    "localAtomics": [
      "@keyframes ava-pulse",
      "@keyframes cc-msg-in",
      "@keyframes cc-typing",
      "@keyframes cg-spin"
    ]
  },
  "faq.html": {
    "chatWidget": true,
    "stylesCss": [
      "*, *::before, *::after",
      "html, body",
      "img",
      "button",
      "a",
      ":root",
      "body",
      ".site-shell",
      ".page-stack",
      ".site-nav",
      ".nav-pill",
      ".nav-link",
      ".nav-link::after",
      ".nav-link:hover",
      ".nav-link:hover::after",
      ".nav-link.active",
      ".contact-widget",
      ".contact-widget-btn",
      ".contact-widget-btn:hover",
      ".contact-widget-ava-wrap",
      ".contact-widget-avatar",
      ".contact-widget-avatar img",
      ".contact-widget-dot",
      ".contact-widget-text",
      ".contact-widget-title",
      ".contact-widget-online",
      ".mobile-top",
      ".mobile-wordmark",
      ".mobile-burger",
      ".mobile-burger:active",
      ".burger-bar",
      ".mobile-nav-overlay",
      ".mobile-nav-link",
      ".mobile-nav-link:hover, .mobile-nav-link:active"
    ],
    "local": [
      ".faq-hero",
      ".faq-hero h1",
      ".faq-hero-sub",
      ".faq-wrap",
      ".faq-list",
      ".faq-list .faq-item:nth-child(5n+1):not(:first-child):not(:nth-child(21))",
      ".faq-list .faq-item:nth-child(5n+1):not(:first-child):not(:nth-child(21))::before",
      ".faq-item",
      ".faq-item::after",
      ".faq-q",
      ".faq-q:hover",
      ".faq-q-text",
      ".faq-q-icon",
      ".faq-q-icon svg,.faq-q-icon svg polyline",
      ".faq-q-icon svg",
      ".faq-a",
      ".faq-a-inner",
      ".faq-a-inner p",
      ".faq-a-inner p:first-child"
    ],
    "localAtomics": []
  },
  "flower-wall-guide/index.html": {
    "chatWidget": true,
    "stylesCss": [
      "*, *::before, *::after",
      "html, body",
      "img",
      "button",
      "a",
      ":root",
      "body",
      ".site-shell",
      ".page-stack",
      ".site-nav",
      ".nav-pill",
      ".nav-link",
      ".nav-link::after",
      ".nav-link:hover",
      ".nav-link:hover::after",
      ".nav-link.active",
      ".contact-widget",
      ".contact-widget-btn",
      ".contact-widget-btn:hover",
      ".contact-widget-ava-wrap",
      ".contact-widget-avatar",
      ".contact-widget-avatar img",
      ".contact-widget-dot",
      ".contact-widget-text",
      ".contact-widget-title",
      ".contact-widget-online",
      ".mobile-top",
      ".mobile-wordmark",
      ".mobile-burger",
      ".mobile-burger:active",
      ".burger-bar",
      ".mobile-nav-overlay",
      ".mobile-nav-link",
      ".mobile-nav-link:hover, .mobile-nav-link:active"
    ],
    "local": [
      ".tips-hero",
      ".tips-hero h1",
      ".tips-hero h2",
      ".tips-grid",
      ".tips-card",
      ".tips-card-img-wrap",
      ".tips-card-img",
      ".tips-card-img-wrap::after",
      ".tips-card-body",
      ".tips-card-meta",
      ".tips-card-title",
      ".tips-card-desc",
      ".tips-card-link",
      ".tips-card-link:hover",
      ".tips-card-link svg"
    ],
    "localAtomics": []
  },
  "flower-wall-guide/real-touch-vs-silk-flower-wall/index.html": {
    "chatWidget": true,
    "stylesCss": [
      "*, *::before, *::after",
      "html, body",
      "img",
      "button",
      "a",
      ":root",
      "body",
      ".site-shell",
      ".page-stack",
      ".site-nav",
      ".nav-pill",
      ".nav-link",
      ".nav-link::after",
      ".nav-link:hover",
      ".nav-link:hover::after",
      ".nav-link.active",
      ".contact-widget",
      ".contact-widget-btn",
      ".contact-widget-btn:hover",
      ".contact-widget-ava-wrap",
      ".contact-widget-avatar",
      ".contact-widget-avatar img",
      ".contact-widget-dot",
      ".contact-widget-text",
      ".contact-widget-title",
      ".contact-widget-online",
      ".mobile-top",
      ".mobile-wordmark",
      ".mobile-burger",
      ".mobile-burger:active",
      ".burger-bar",
      ".mobile-nav-overlay",
      ".mobile-nav-link",
      ".mobile-nav-link:hover, .mobile-nav-link:active"
    ],
    "local": [
      ".tips-breadcrumb",
      ".tips-breadcrumb a",
      ".tips-breadcrumb a:hover",
      ".tips-breadcrumb-sep",
      ".tips-breadcrumb-current",
      ".article-wrap",
      ".article-hero-img",
      ".article-header",
      ".article-header h1",
      ".article-body",
      ".article-body p"
    ],
    "localAtomics": []
  },
  "flower-walls/burgundy-flower-wall/index.html": {
    "chatWidget": true,
    "stylesCss": [
      "*, *::before, *::after",
      "html, body",
      "img",
      "button",
      "a",
      ":root",
      "body",
      ".site-shell",
      ".page-stack",
      ".site-nav",
      ".nav-pill",
      ".nav-link",
      ".nav-link::after",
      ".nav-link:hover",
      ".nav-link:hover::after",
      ".nav-link.active",
      ".contact-widget",
      ".contact-widget-btn",
      ".contact-widget-btn:hover",
      ".contact-widget-ava-wrap",
      ".contact-widget-avatar",
      ".contact-widget-avatar img",
      ".contact-widget-dot",
      ".contact-widget-text",
      ".contact-widget-title",
      ".contact-widget-online",
      ".pv2-wrap",
      ".pv2-header",
      ".pv2-header-top",
      ".pv2-header-left",
      ".pv2-name",
      ".pv2-topbar-tabs",
      ".pv2-topbar-tab",
      ".pv2-topbar-tab svg",
      ".pv2-topbar-tab:hover",
      ".pv2-topbar-tab.active",
      ".pv2-media-zone",
      ".pv2-pane",
      ".pv2-pane.active",
      ".pv2-img",
      ".pv2-img.active",
      ".pv2-arrow",
      ".pv2-arrow svg",
      ".pv2-arrow.prev",
      ".pv2-arrow.next",
      ".pv2-arrow:hover",
      ".pv2-counter",
      ".pv2-content-tabs",
      ".pv2-ctab",
      ".pv2-ctab:hover",
      ".pv2-ctab.active",
      ".mobile-top",
      ".mobile-wordmark",
      ".mobile-burger",
      ".mobile-burger:active",
      ".burger-bar",
      ".mobile-nav-overlay",
      ".mobile-nav-link",
      ".mobile-nav-link:hover, .mobile-nav-link:active",
      ".lighting-bar-label",
      ".lighting-bar-btns",
      ".product-desc",
      ".pv2-tab:hover .pv2-tip, .pv2-light-btn:hover .pv2-tip, .pv2-palette-btn:hover .pv2-tip",
      ".pv2-light-btn",
      ".pv2-light-btn:hover",
      ".pv2-light-btn.active",
      ".pv2-light-btn svg",
      ".pv2-palette-panel",
      ".pv2-palette-grid",
      ".pv2-swatch-item",
      ".pv2-swatch-dot",
      ".pv2-swatch-dot:hover",
      ".pv2-swatch-name",
      ".pv2-controls-bar",
      ".pv2-bar-sep",
      ".pv2-rainbow-btn",
      ".pv2-rainbow-btn::after",
      ".pv2-rainbow-btn:hover",
      ".pv2-lighting-bar .pv2-light-btn, .pv2-controls-bar .pv2-light-btn",
      ".pv2-lighting-bar .pv2-light-btn.active, .pv2-controls-bar .pv2-light-btn.active",
      ".pv2-lighting-bar .pv2-light-btn:hover, .pv2-controls-bar .pv2-light-btn:hover",
      ".pv2-thumbs-lighting-row",
      ".pv2-thumbs-lighting-row .pv2-thumbs-row",
      ".pv2-thumbs-row",
      ".pv2-thumb",
      ".pv2-thumb.active",
      ".pv2-thumb:hover",
      ".pv2-info-strip",
      ".pv2-ctab-pane",
      ".pv2-ctab-pane.active",
      ".pv2-info-grid",
      ".pv2-info-left",
      ".pv2-size-popup",
      ".pv2-size-popup::after",
      ".pv2-size-popup h4",
      ".pv2-popup-sizes",
      ".pv2-popup-size-row",
      ".pv2-popup-size-name",
      ".pv2-popup-size-desc",
      ".pv2-rainbow-wrap",
      ".pv2-rainbow-wrap:hover .pv2-rainbow-tip"
    ],
    "local": [
      ".pbcr",
      ".pbcr a",
      ".pbcr a:hover",
      ".pbcr-sep",
      ".pbcr-current",
      ".pv2-product-subtitle",
      ".pv2-header-top .pv2-content-tabs"
    ],
    "localAtomics": []
  },
  "flower-walls/green-flower-wall/index.html": {
    "chatWidget": true,
    "stylesCss": [
      "*, *::before, *::after",
      "html, body",
      "img",
      "button",
      "a",
      ":root",
      "body",
      ".site-shell",
      ".page-stack",
      ".site-nav",
      ".nav-pill",
      ".nav-link",
      ".nav-link::after",
      ".nav-link:hover",
      ".nav-link:hover::after",
      ".nav-link.active",
      ".contact-widget",
      ".contact-widget-btn",
      ".contact-widget-btn:hover",
      ".contact-widget-ava-wrap",
      ".contact-widget-avatar",
      ".contact-widget-avatar img",
      ".contact-widget-dot",
      ".contact-widget-text",
      ".contact-widget-title",
      ".contact-widget-online",
      ".pv2-wrap",
      ".pv2-header",
      ".pv2-header-top",
      ".pv2-header-left",
      ".pv2-name",
      ".pv2-topbar-tabs",
      ".pv2-topbar-tab",
      ".pv2-topbar-tab svg",
      ".pv2-topbar-tab:hover",
      ".pv2-topbar-tab.active",
      ".pv2-media-zone",
      ".pv2-pane",
      ".pv2-pane.active",
      ".pv2-img",
      ".pv2-img.active",
      ".pv2-arrow",
      ".pv2-arrow svg",
      ".pv2-arrow.prev",
      ".pv2-arrow.next",
      ".pv2-arrow:hover",
      ".pv2-counter",
      ".pv2-content-tabs",
      ".pv2-ctab",
      ".pv2-ctab:hover",
      ".pv2-ctab.active",
      ".mobile-top",
      ".mobile-wordmark",
      ".mobile-burger",
      ".mobile-burger:active",
      ".burger-bar",
      ".mobile-nav-overlay",
      ".mobile-nav-link",
      ".mobile-nav-link:hover, .mobile-nav-link:active",
      ".lighting-bar-label",
      ".lighting-bar-btns",
      ".product-desc",
      ".pv2-tab:hover .pv2-tip, .pv2-light-btn:hover .pv2-tip, .pv2-palette-btn:hover .pv2-tip",
      ".pv2-light-btn",
      ".pv2-light-btn:hover",
      ".pv2-light-btn.active",
      ".pv2-light-btn svg",
      ".pv2-palette-panel",
      ".pv2-palette-grid",
      ".pv2-swatch-item",
      ".pv2-swatch-dot",
      ".pv2-swatch-dot:hover",
      ".pv2-swatch-name",
      ".pv2-controls-bar",
      ".pv2-bar-sep",
      ".pv2-rainbow-btn",
      ".pv2-rainbow-btn::after",
      ".pv2-rainbow-btn:hover",
      ".pv2-lighting-bar .pv2-light-btn, .pv2-controls-bar .pv2-light-btn",
      ".pv2-lighting-bar .pv2-light-btn.active, .pv2-controls-bar .pv2-light-btn.active",
      ".pv2-lighting-bar .pv2-light-btn:hover, .pv2-controls-bar .pv2-light-btn:hover",
      ".pv2-thumbs-lighting-row",
      ".pv2-thumbs-lighting-row .pv2-thumbs-row",
      ".pv2-thumbs-row",
      ".pv2-thumb",
      ".pv2-thumb.active",
      ".pv2-thumb:hover",
      ".pv2-info-strip",
      ".pv2-ctab-pane",
      ".pv2-ctab-pane.active",
      ".pv2-info-grid",
      ".pv2-info-left",
      ".pv2-size-popup",
      ".pv2-size-popup::after",
      ".pv2-size-popup h4",
      ".pv2-popup-sizes",
      ".pv2-popup-size-row",
      ".pv2-popup-size-name",
      ".pv2-popup-size-desc",
      ".pv2-rainbow-wrap",
      ".pv2-rainbow-wrap:hover .pv2-rainbow-tip"
    ],
    "local": [
      ".pbcr",
      ".pbcr a",
      ".pbcr a:hover",
      ".pbcr-sep",
      ".pbcr-current",
      ".pv2-product-subtitle",
      ".pv2-header-top .pv2-content-tabs"
    ],
    "localAtomics": []
  },
  "flower-walls/pink-flower-wall/index.html": {
    "chatWidget": true,
    "stylesCss": [
      "*, *::before, *::after",
      "html, body",
      "img",
      "button",
      "a",
      ":root",
      "body",
      ".site-shell",
      ".page-stack",
      ".site-nav",
      ".nav-pill",
      ".nav-link",
      ".nav-link::after",
      ".nav-link:hover",
      ".nav-link:hover::after",
      ".nav-link.active",
      ".contact-widget",
      ".contact-widget-btn",
      ".contact-widget-btn:hover",
      ".contact-widget-ava-wrap",
      ".contact-widget-avatar",
      ".contact-widget-avatar img",
      ".contact-widget-dot",
      ".contact-widget-text",
      ".contact-widget-title",
      ".contact-widget-online",
      ".pv2-wrap",
      ".pv2-header",
      ".pv2-header-top",
      ".pv2-header-left",
      ".pv2-name",
      ".pv2-topbar-tabs",
      ".pv2-topbar-tab",
      ".pv2-topbar-tab svg",
      ".pv2-topbar-tab:hover",
      ".pv2-topbar-tab.active",
      ".pv2-media-zone",
      ".pv2-pane",
      ".pv2-pane.active",
      ".pv2-img",
      ".pv2-img.active",
      ".pv2-arrow",
      ".pv2-arrow svg",
      ".pv2-arrow.prev",
      ".pv2-arrow.next",
      ".pv2-arrow:hover",
      ".pv2-counter",
      ".pv2-content-tabs",
      ".pv2-ctab",
      ".pv2-ctab:hover",
      ".pv2-ctab.active",
      ".mobile-top",
      ".mobile-wordmark",
      ".mobile-burger",
      ".mobile-burger:active",
      ".burger-bar",
      ".mobile-nav-overlay",
      ".mobile-nav-link",
      ".mobile-nav-link:hover, .mobile-nav-link:active",
      ".lighting-bar-label",
      ".lighting-bar-btns",
      ".product-desc",
      ".pv2-tab:hover .pv2-tip, .pv2-light-btn:hover .pv2-tip, .pv2-palette-btn:hover .pv2-tip",
      ".pv2-light-btn",
      ".pv2-light-btn:hover",
      ".pv2-light-btn.active",
      ".pv2-light-btn svg",
      ".pv2-palette-panel",
      ".pv2-palette-grid",
      ".pv2-swatch-item",
      ".pv2-swatch-dot",
      ".pv2-swatch-dot:hover",
      ".pv2-swatch-name",
      ".pv2-controls-bar",
      ".pv2-bar-sep",
      ".pv2-rainbow-btn",
      ".pv2-rainbow-btn::after",
      ".pv2-rainbow-btn:hover",
      ".pv2-lighting-bar .pv2-light-btn, .pv2-controls-bar .pv2-light-btn",
      ".pv2-lighting-bar .pv2-light-btn.active, .pv2-controls-bar .pv2-light-btn.active",
      ".pv2-lighting-bar .pv2-light-btn:hover, .pv2-controls-bar .pv2-light-btn:hover",
      ".pv2-thumbs-lighting-row",
      ".pv2-thumbs-lighting-row .pv2-thumbs-row",
      ".pv2-thumbs-row",
      ".pv2-thumb",
      ".pv2-thumb.active",
      ".pv2-thumb:hover",
      ".pv2-info-strip",
      ".pv2-ctab-pane",
      ".pv2-ctab-pane.active",
      ".pv2-info-grid",
      ".pv2-info-left",
      ".pv2-size-popup",
      ".pv2-size-popup::after",
      ".pv2-size-popup h4",
      ".pv2-popup-sizes",
      ".pv2-popup-size-row",
      ".pv2-popup-size-name",
      ".pv2-rainbow-wrap",
      ".pv2-rainbow-wrap:hover .pv2-rainbow-tip"
    ],
    "local": [
      ".pbcr",
      ".pbcr a",
      ".pbcr a:hover",
      ".pbcr-sep",
      ".pbcr-current",
      ".pv2-product-subtitle",
      ".pv2-header-top .pv2-content-tabs"
    ],
    "localAtomics": []
  },
  "flower-walls/white-flower-wall/index.html": {
    "chatWidget": true,
    "stylesCss": [
      "*, *::before, *::after",
      "html, body",
      "img",
      "button",
      "a",
      ":root",
      "body",
      ".site-shell",
      ".page-stack",
      ".site-nav",
      ".nav-pill",
      ".nav-link",
      ".nav-link::after",
      ".nav-link:hover",
      ".nav-link:hover::after",
      ".nav-link.active",
      ".contact-widget",
      ".contact-widget-btn",
      ".contact-widget-btn:hover",
      ".contact-widget-ava-wrap",
      ".contact-widget-avatar",
      ".contact-widget-avatar img",
      ".contact-widget-dot",
      ".contact-widget-text",
      ".contact-widget-title",
      ".contact-widget-online",
      ".pv2-wrap",
      ".pv2-header",
      ".pv2-header-top",
      ".pv2-header-left",
      ".pv2-name",
      ".pv2-topbar-tabs",
      ".pv2-topbar-tab",
      ".pv2-topbar-tab svg",
      ".pv2-topbar-tab:hover",
      ".pv2-topbar-tab.active",
      ".pv2-media-zone",
      ".pv2-pane",
      ".pv2-pane.active",
      ".pv2-img",
      ".pv2-img.active",
      ".pv2-arrow",
      ".pv2-arrow svg",
      ".pv2-arrow.prev",
      ".pv2-arrow.next",
      ".pv2-arrow:hover",
      ".pv2-counter",
      ".pv2-content-tabs",
      ".pv2-ctab",
      ".pv2-ctab:hover",
      ".pv2-ctab.active",
      ".mobile-top",
      ".mobile-wordmark",
      ".mobile-burger",
      ".mobile-burger:active",
      ".burger-bar",
      ".mobile-nav-overlay",
      ".mobile-nav-link",
      ".mobile-nav-link:hover, .mobile-nav-link:active",
      ".lighting-bar-label",
      ".lighting-bar-btns",
      ".product-desc",
      ".pv2-tab:hover .pv2-tip, .pv2-light-btn:hover .pv2-tip, .pv2-palette-btn:hover .pv2-tip",
      ".pv2-light-btn",
      ".pv2-light-btn:hover",
      ".pv2-light-btn.active",
      ".pv2-light-btn svg",
      ".pv2-palette-panel",
      ".pv2-palette-grid",
      ".pv2-swatch-item",
      ".pv2-swatch-dot",
      ".pv2-swatch-dot:hover",
      ".pv2-swatch-name",
      ".pv2-controls-bar",
      ".pv2-bar-sep",
      ".pv2-rainbow-btn",
      ".pv2-rainbow-btn::after",
      ".pv2-rainbow-btn:hover",
      ".pv2-lighting-bar .pv2-light-btn, .pv2-controls-bar .pv2-light-btn",
      ".pv2-lighting-bar .pv2-light-btn.active, .pv2-controls-bar .pv2-light-btn.active",
      ".pv2-lighting-bar .pv2-light-btn:hover, .pv2-controls-bar .pv2-light-btn:hover",
      ".pv2-thumbs-lighting-row",
      ".pv2-thumbs-lighting-row .pv2-thumbs-row",
      ".pv2-thumbs-row",
      ".pv2-thumb",
      ".pv2-thumb.active",
      ".pv2-thumb:hover",
      ".pv2-info-strip",
      ".pv2-ctab-pane",
      ".pv2-ctab-pane.active",
      ".pv2-info-grid",
      ".pv2-info-left",
      ".pv2-size-popup",
      ".pv2-size-popup::after",
      ".pv2-size-popup h4",
      ".pv2-popup-sizes",
      ".pv2-popup-size-row",
      ".pv2-popup-size-name",
      ".pv2-popup-size-desc",
      ".pv2-rainbow-wrap",
      ".pv2-rainbow-wrap:hover .pv2-rainbow-tip"
    ],
    "local": [
      ".pbcr",
      ".pbcr a",
      ".pbcr a:hover",
      ".pbcr-sep",
      ".pbcr-current",
      ".pv2-product-subtitle",
      ".pv2-header-top .pv2-content-tabs"
    ],
    "localAtomics": []
  },
  "gallery.html": {
    "chatWidget": true,
    "stylesCss": [
      "*, *::before, *::after",
      "html, body",
      "img",
      "button",
      "a",
      ":root",
      "body",
      ".site-shell",
      ".page-stack",
      ".site-nav",
      ".nav-pill",
      ".nav-link",
      ".nav-link::after",
      ".nav-link:hover",
      ".nav-link:hover::after",
      ".nav-link.active",
      ".collections",
      ".collections-grid",
      ".collection-card",
      ".collection-card:hover",
      ".collection-card-inner",
      ".collection-card-inner::before",
      ".collection-card-inner img",
      ".collection-caption",
      ".collection-caption-title",
      ".collection-arrow",
      ".collection-card:hover .collection-arrow",
      ".collection-arrow svg",
      ".contact-widget",
      ".contact-widget-btn",
      ".contact-widget-btn:hover",
      ".contact-widget-ava-wrap",
      ".contact-widget-avatar",
      ".contact-widget-avatar img",
      ".contact-widget-dot",
      ".contact-widget-text",
      ".contact-widget-title",
      ".contact-widget-online",
      ".mobile-top",
      ".mobile-wordmark",
      ".mobile-burger",
      ".mobile-burger:active",
      ".burger-bar",
      ".mobile-nav-overlay",
      ".mobile-nav-link",
      ".mobile-nav-link:hover, .mobile-nav-link:active"
    ],
    "local": [
      ".gallery-page-hero",
      ".gallery-page-hero h1",
      ".gallery-page-hero p"
    ],
    "localAtomics": []
  },
  "index.html": {
    "chatWidget": true,
    "stylesCss": [
      "*, *::before, *::after",
      "html, body",
      "img",
      "button",
      "a",
      ":root",
      "body",
      ".eyebrow",
      ".site-shell",
      ".page-stack",
      ".site-nav",
      ".nav-pill",
      ".nav-link",
      ".nav-link::after",
      ".nav-link:hover",
      ".nav-link:hover::after",
      ".hero",
      ".hero-wordmark",
      ".wordmark",
      ".wordmark:hover",
      ".wordmark-tagline",
      ".hero-wordmark .eyebrow",
      ".tagline-rule",
      ".hero-yt-wrap",
      ".hero-yt-overlay",
      ".hero-copy",
      ".hero-copy p",
      ".form-row",
      ".form-field",
      ".form-field label",
      ".form-req",
      ".form-input, .form-textarea",
      ".form-input::placeholder, .form-textarea::placeholder",
      ".form-input:focus, .form-textarea:focus",
      ".cc-inquiry-wrap .form-row",
      ".cc-inquiry-wrap .form-field",
      ".cc-inquiry-wrap .form-field label",
      ".cc-inquiry-wrap .form-input, .cc-inquiry-wrap .form-textarea, .cc-inquiry-wrap .form-select",
      ".cc-inquiry-wrap .form-input:focus, .cc-inquiry-wrap .form-textarea:focus, .cc-inquiry-wrap .form-select:focus",
      ".contact-widget",
      ".contact-widget-btn",
      ".contact-widget-btn:hover",
      ".contact-widget-ava-wrap",
      ".contact-widget-avatar",
      ".contact-widget-avatar img",
      ".contact-widget-dot",
      ".contact-widget-text",
      ".contact-widget-title",
      ".contact-widget-online",
      ".hero-phrases",
      ".hero-phrase",
      ".mobile-top",
      ".mobile-wordmark",
      ".mobile-burger",
      ".mobile-burger:active",
      ".burger-bar",
      ".mobile-nav-overlay",
      ".mobile-nav-link",
      ".mobile-nav-link:hover, .mobile-nav-link:active",
      ".form-select",
      ".form-select:focus",
      ".form-select option",
      ".form-field--extended, .form-row--extended",
      ".hero--videobg",
      ".hero--videobg .hero-yt-wrap",
      ".hero--videobg .hero-bg-video",
      ".hero--videobg .hero-yt-overlay",
      ".hero--videobg .hero-wordmark, .hero--videobg .hero-bottom-group",
      ".hero-bottom-group",
      ".hero--videobg .tagline-rule",
      ".hero--videobg .hero-wordmark .eyebrow",
      ".hero--videobg .hero-wordmark .wordmark",
      ".hero--videobg .hero-copy p",
      ".hero--videobg .hero-phrase",
      ".section-title",
      ".section-title h2",
      ".collections",
      ".section-sep",
      ".hero-plate img, .hero-plate video, .hero-yt-wrap",
      ".hero-wordmark .wordmark",
      ".rv-arrow",
      ".hero--videobg .hero-wordmark",
      ".hero--videobg .hero-phrases",
      ".hero--videobg .hero-bottom-group",
      ".hero--videobg .hero-copy",
      ".contact-widget.cw-scroll-managed",
      ".contact-widget.cw-scroll-managed.cw-visible"
    ],
    "local": [
      ".rv-arrow svg",
      ".rv-arrow:hover",
      ".rv-arrow--prev",
      ".rv-arrow--next"
    ],
    "localAtomics": []
  },
  "kind-words.html": {
    "chatWidget": true,
    "stylesCss": [
      "*, *::before, *::after",
      "html, body",
      "img",
      "button",
      "a",
      ":root",
      "body",
      ".site-shell",
      ".page-stack",
      ".site-nav",
      ".nav-pill",
      ".nav-link",
      ".nav-link::after",
      ".nav-link:hover",
      ".nav-link:hover::after",
      ".nav-link.active",
      ".contact-widget",
      ".contact-widget-btn",
      ".contact-widget-btn:hover",
      ".contact-widget-ava-wrap",
      ".contact-widget-avatar",
      ".contact-widget-avatar img",
      ".contact-widget-dot",
      ".contact-widget-text",
      ".contact-widget-title",
      ".contact-widget-online",
      ".mobile-top",
      ".mobile-wordmark",
      ".mobile-burger",
      ".mobile-burger:active",
      ".burger-bar",
      ".mobile-nav-overlay",
      ".mobile-nav-link",
      ".mobile-nav-link:hover, .mobile-nav-link:active"
    ],
    "local": [
      ".kw-page-header",
      ".kw-page-header h1",
      ".kw-intro",
      ".kw-section",
      ".kw-grid",
      ".kw-card",
      ".kw-card.is-visible",
      ".kw-photo-wrap",
      ".kw-photo-wrap::after",
      ".kw-card-photo",
      ".kw-card-body",
      ".kw-quote-mark",
      ".kw-text"
    ],
    "localAtomics": []
  },
  "locations.html": {
    "chatWidget": true,
    "stylesCss": [
      "*, *::before, *::after",
      "html, body",
      "img",
      "button",
      "a",
      ":root",
      "body",
      ".site-shell",
      ".page-stack",
      ".site-nav",
      ".nav-pill",
      ".nav-link",
      ".nav-link::after",
      ".nav-link:hover",
      ".nav-link:hover::after",
      ".contact-widget",
      ".contact-widget-btn",
      ".contact-widget-btn:hover",
      ".contact-widget-ava-wrap",
      ".contact-widget-avatar",
      ".contact-widget-avatar img",
      ".contact-widget-dot",
      ".contact-widget-text",
      ".contact-widget-title",
      ".contact-widget-online",
      ".page-stack--locations",
      ".loc-map-caption",
      ".mobile-top",
      ".mobile-wordmark",
      ".mobile-burger",
      ".mobile-burger:active",
      ".burger-bar",
      ".mobile-nav-overlay",
      ".mobile-nav-link",
      ".mobile-nav-link:hover, .mobile-nav-link:active"
    ],
    "local": [
      ".loc-header",
      ".loc-header h1",
      ".loc-intro",
      ".loc-map-frame",
      ".loc-map-inset",
      ".loc-map-caption-title",
      ".loc-map-caption-body",
      ".loc-map-svg",
      ".city-pin",
      ".city-pin .pin-aura",
      ".city-pin:hover .pin-aura",
      ".city-pin .pin-core",
      ".city-pin:hover .pin-core",
      ".city-pin--t1 .pin-core",
      ".pin-pulse,.pin-pulse-2",
      ".pin-pulse",
      ".pin-pulse-2",
      ".pin-label",
      ".pin-label--t1",
      ".pin-label--t2",
      ".pin-label--t3",
      ".loc-stats",
      ".loc-stat",
      ".loc-stat + .loc-stat::before",
      ".loc-stat-num",
      ".loc-stat-lbl",
      ".loc-stat:nth-child(2n)::before"
    ],
    "localAtomics": [
      "@keyframes map-pulse"
    ]
  },
  "privacy-policy.html": {
    "chatWidget": true,
    "stylesCss": [
      "*, *::before, *::after",
      "html, body",
      "img",
      "button",
      "a",
      ":root",
      "body",
      ".site-shell",
      ".page-stack",
      ".site-nav",
      ".nav-pill",
      ".nav-link",
      ".nav-link::after",
      ".nav-link:hover",
      ".nav-link:hover::after",
      ".contact-widget",
      ".contact-widget-btn",
      ".contact-widget-btn:hover",
      ".contact-widget-ava-wrap",
      ".contact-widget-avatar",
      ".contact-widget-avatar img",
      ".contact-widget-dot",
      ".contact-widget-text",
      ".contact-widget-title",
      ".contact-widget-online",
      ".mobile-top",
      ".mobile-wordmark",
      ".mobile-burger",
      ".mobile-burger:active",
      ".burger-bar",
      ".mobile-nav-overlay",
      ".mobile-nav-link",
      ".mobile-nav-link:hover, .mobile-nav-link:active"
    ],
    "local": [
      ".doc-page",
      ".doc-eyebrow",
      ".doc-title",
      ".doc-lead",
      ".doc-section",
      ".doc-section-num",
      ".doc-section h2",
      ".doc-section p",
      ".doc-section ul",
      ".doc-section ul li",
      ".doc-section ul li::before",
      ".doc-section strong"
    ],
    "localAtomics": []
  },
  "product.html": {
    "chatWidget": true,
    "stylesCss": [
      "*, *::before, *::after",
      "html, body",
      "img",
      "button",
      "a",
      ":root",
      "body",
      ".site-shell",
      ".page-stack",
      ".site-nav",
      ".nav-pill",
      ".nav-link",
      ".nav-link::after",
      ".nav-link:hover",
      ".nav-link:hover::after",
      ".nav-link.active",
      ".contact-widget",
      ".contact-widget-btn",
      ".contact-widget-btn:hover",
      ".contact-widget-ava-wrap",
      ".contact-widget-avatar",
      ".contact-widget-avatar img",
      ".contact-widget-dot",
      ".contact-widget-text",
      ".contact-widget-title",
      ".contact-widget-online",
      ".product-breadcrumb",
      ".product-breadcrumb a",
      ".product-breadcrumb a:hover",
      ".product-eyebrow",
      ".pv2-wrap",
      ".pv2-header",
      ".pv2-header-top",
      ".pv2-header-left",
      ".pv2-name",
      ".pv2-topbar-tabs",
      ".pv2-topbar-tab",
      ".pv2-topbar-tab svg",
      ".pv2-topbar-tab:hover",
      ".pv2-topbar-tab.active",
      ".pv2-media-zone",
      ".pv2-pane",
      ".pv2-pane.active",
      ".pv2-img",
      ".pv2-img.active",
      ".pv2-arrow",
      ".pv2-arrow svg",
      ".pv2-arrow.prev",
      ".pv2-arrow.next",
      ".pv2-arrow:hover",
      ".pv2-counter",
      ".pv2-content-tabs",
      ".pv2-ctab",
      ".pv2-ctab:hover",
      ".pv2-ctab.active",
      ".mobile-top",
      ".mobile-wordmark",
      ".mobile-burger",
      ".mobile-burger:active",
      ".burger-bar",
      ".mobile-nav-overlay",
      ".mobile-nav-link",
      ".mobile-nav-link:hover, .mobile-nav-link:active",
      ".lighting-bar-label",
      ".lighting-bar-btns",
      ".product-desc",
      ".pv2-tab:hover .pv2-tip, .pv2-light-btn:hover .pv2-tip, .pv2-palette-btn:hover .pv2-tip",
      ".pv2-light-btn",
      ".pv2-light-btn:hover",
      ".pv2-light-btn.active",
      ".pv2-light-btn svg",
      ".pv2-palette-panel",
      ".pv2-palette-grid",
      ".pv2-swatch-item",
      ".pv2-swatch-dot",
      ".pv2-swatch-dot:hover",
      ".pv2-swatch-name",
      ".pv2-controls-bar",
      ".pv2-bar-sep",
      ".pv2-rainbow-btn",
      ".pv2-rainbow-btn::after",
      ".pv2-rainbow-btn:hover",
      ".pv2-lighting-bar .pv2-light-btn, .pv2-controls-bar .pv2-light-btn",
      ".pv2-lighting-bar .pv2-light-btn.active, .pv2-controls-bar .pv2-light-btn.active",
      ".pv2-lighting-bar .pv2-light-btn:hover, .pv2-controls-bar .pv2-light-btn:hover",
      ".pv2-thumbs-lighting-row",
      ".pv2-thumbs-lighting-row .pv2-thumbs-row",
      ".pv2-thumbs-row",
      ".pv2-thumb",
      ".pv2-thumb.active",
      ".pv2-thumb:hover",
      ".pv2-info-strip",
      ".pv2-ctab-pane",
      ".pv2-ctab-pane.active",
      ".pv2-info-grid",
      ".pv2-info-left",
      ".pv2-size-popup",
      ".pv2-size-popup::after",
      ".pv2-size-popup h4",
      ".pv2-popup-sizes",
      ".pv2-popup-size-row",
      ".pv2-popup-size-name",
      ".pv2-popup-size-desc",
      ".pv2-rainbow-wrap",
      ".pv2-rainbow-wrap:hover .pv2-rainbow-tip"
    ],
    "local": [],
    "localAtomics": []
  },
  "terms-of-use.html": {
    "chatWidget": true,
    "stylesCss": [
      "*, *::before, *::after",
      "html, body",
      "img",
      "button",
      "a",
      ":root",
      "body",
      ".site-shell",
      ".page-stack",
      ".site-nav",
      ".nav-pill",
      ".nav-link",
      ".nav-link::after",
      ".nav-link:hover",
      ".nav-link:hover::after",
      ".contact-widget",
      ".contact-widget-btn",
      ".contact-widget-btn:hover",
      ".contact-widget-ava-wrap",
      ".contact-widget-avatar",
      ".contact-widget-avatar img",
      ".contact-widget-dot",
      ".contact-widget-text",
      ".contact-widget-title",
      ".contact-widget-online",
      ".mobile-top",
      ".mobile-wordmark",
      ".mobile-burger",
      ".mobile-burger:active",
      ".burger-bar",
      ".mobile-nav-overlay",
      ".mobile-nav-link",
      ".mobile-nav-link:hover, .mobile-nav-link:active"
    ],
    "local": [
      ".doc-page",
      ".doc-eyebrow",
      ".doc-title",
      ".doc-subtitle",
      ".doc-lead",
      ".doc-section",
      ".doc-section-num",
      ".doc-section h2",
      ".doc-section p",
      ".doc-section ul",
      ".doc-section ul li",
      ".doc-section ul li::before",
      ".doc-section strong"
    ],
    "localAtomics": []
  }
};
